### ISSUE TITLE
Unintuitive Default implementations for requests

### ISSUE THREAD

**Issue by EpokTarren** [ion232/lichess-api#64]
Currently the following code compiles, it does not have what I would imagine is the expected behaviour, instead the final line will always error, this part of the crate API feels like a footgun.

```rs
let client = reqwest::ClientBuilder::new().build()?;
let api = lichess_api::LichessApi::new(client, None);

api.get_profile(Default::default())?;
```

My suggestion is that `model::Request` shouldn't implement `Default` directly, instead for types such as `model::account::profile::GetRequest` should implement so that the request is properly formed, mainly the path is currently missing. For request types such as `model::messaging::inbox::PostRequest` it would make sense not to implement `Default` at all.
Do methods which take no arguments need a to accept a request type or could it be generated in the method body?

For methods such as `client::LichessApi::tv_channel_games` that only have one required parameter, could they accept only that in addition to the full type using `From` / `Into`, example code below.

```rs
impl From<ChannelName> for GetRequest {
    fn from(channel: ChannelName) -> GetRequest {
        GetRequest::new(channel, None)
    }
}
```

```rs
impl LichessApi<reqwest::Client> {
    pub async fn tv_channels(&self, request: impl Into<channels::GetRequest>) -> Result<Channels> {
        self.get_single_model(request.into()).await
    }
}
```

Would these changes be desirable contributions to the project?

**Comment by ion232** [comment]
- You raise a good point regarding deriving `Default` for `model::Request`. IIRC I originally did this to just cut down on boilerplate, hence the many instances of `..Default::default()`. I think it should be removed and changes made as you suggest, although ideally in a way that saves on boilerplate, if possible.  
- I also like the `impl Into<GetRequest>` idea; I was aware that many of these requests were quite simple, but didn't realise you could do this. I wanted to make sure the signature of the API methods was relatively uniform, constant, and relied on a single source of truth (one struct). This change would make it easier to construct them while also preserving that.
- With regard to `Request`s that are simply constructed and passed through, I agree it would make sense to just move them into the method body instead.

Thanks for your feedback :)
